apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::065062300572:role/eksctl-simplejwtapi-nodegroup-ng-NodeInstanceRole-95BU7H2H8XXA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::065062300572:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-23T05:40:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "927"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4f83b976-081b-4646-be56-a0ea478536c5
