apiVersion: v1
kind: Service
metadata:
  name: simplejwtapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simplejwtapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplejwtapi
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: simplejwtapi
  template:
    metadata:
      labels:
        app: simplejwtapi
    spec:
      containers:
        - name: simplejwtapi
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
          - name: JWT_SECRET
            value: JWT_SECRET_VALUE
          ports:
            - containerPort: 8080
